jenkinsci/workflow-basic-steps-plugin

- src/main/resources/org/jenkinsci/plugins/workflow/steps/RetryStep/help.html
- src/main/resources/org/jenkinsci/plugins/workflow/steps/TimeoutStep/help.html
This answers a question I had in trying to use retry, whether it would actually cause an exception if the block continued to fail.
I looked in the source code and tried this out to confirm that this is what retry does but it would be useful to say it in the help.
> Clarify behaviour of retry step in help and fix English on timeout step help

- src/main/java/org/jenkinsci/plugins/workflow/steps/SleepStep.java
Related to https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/4: I noticed that `sleep` steps were sometimes hanging. Turns out that was another bug, to be filed soon…
@reviewbybees
> [JENKINS-34281] Indicate if we are still sleeping after a resume

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepRunTest.java
let's hold the merge until all the changes for JENKINS-29922 is ready
> [JENKINS-29922] marking a meta step as such

- CORE-STEPS.md
- src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStep.java
- src/main/resources/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStep/help.html
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
Follows up #10.
@reviewbybees esp. @kohsuke, @abayer
> [JENKINS-29922] Deprecating ArtifactArchiverStep when ArtifactArchiver can be used in simplified syntax

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/ToolStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/ToolStepRunTest.java
[JENKINS-37397](https://issues.jenkins-ci.org/browse/JENKINS-37397)
Fall back to allowing descriptor IDs as well.
[JENKINS-37386](https://issues.jenkins-ci.org/browse/JENKINS-37386) is driving getting `@Symbol` on `ToolDescriptor`s, so this will not be hugely useful until that's everywhere, but still, better to do ahead of time than after the fact!
cc @reviewbybees esp @jglick and @oleg-nenashev
> [FIXED JENKINS-37397] Allow use of @Symbols from tools as tool types.

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStepExecution.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
[JENKINS-31931](https://issues.jenkins-ci.org/browse/JENKINS-31931)
Also fixing a buglet that archiving from a nonexistent workspace should not automatically fail, except insofar as archiving no files would. Cf. [JENKINS-28121](https://issues.jenkins-ci.org/browse/JENKINS-28121) which also deals with nonexistent workspaces. Generally it is up to each step which expects a context directory to exist to actually make that directory; otherwise `dir('mayOrMayNotExist') {fileExists 'something'}` would gratuitously `mkdirs`, for example.
@reviewbybees
> [JENKINS-31931] Adding test case

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepRunTest.java
[JENKINS-34637](https://issues.jenkins-ci.org/browse/JENKINS-34637)
Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/76, the actual fix. Incorporates #22 (thanks!).
@reviewbybees
> [JENKINS-34637] Test for timeout bug

- .gitignore
- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStepExecution.java
- src/main/resources/org/jenkinsci/plugins/workflow/steps/RetryStep/help.html
- src/test/java/org/jenkinsci/plugins/workflow/steps/RetryStepTest.java
[JENKINS-41276](https://issues.jenkins-ci.org/browse/JENKINS-41276)
Supersedes #34. Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/20 and https://github.com/jenkinsci/workflow-job-plugin/pull/36.
@reviewbybees
> [JENKINS-41276] Do not retry after user abort

- src/main/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStepExecution.java
Downstream of https://github.com/jenkinsci/jenkins/pull/1485.
@reviewbybees
> Use Functions.printThrowable to provide more legible stack traces in 2.43+

- pom.xml
Attempting to fix [this error](https://ci.jenkins.io/job/Plugins/job/workflow-basic-steps-plugin/job/PR-37/3/testReport/org.jenkinsci.plugins.workflow.steps/TimeoutStepTest/serialForm_2/):
```
…
Resuming build at … after Jenkins restart
No need to sleep any longer
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline
java.lang.IllegalStateException: JENKINS-26137: Jenkins is shutting down
at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.<init>(RiverWriter.java:92)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:431)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:412)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:357)
at …
```
Downstream of …
> [JENKINS-26137] Picking up possible fix for integration testing

- src/main/java/org/jenkinsci/plugins/workflow/steps/WriteFileStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/ReadWriteFileStepTest.java
[JENKINS-27094](https://issues.jenkins-ci.org/browse/JENKINS-27094)
Added in the missing handling to WriteFileStep to have it properly implement the encoding parameter plus a couple of tests to make sure it's working.
> [JENKINS-27094] writeFile encoding parameter

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/EnvStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/MailStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/PwdStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/SleepStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/ToolStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/WriteFileStep.java
- src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/EnvStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/MailStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/PwdStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/ReadWriteFileStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/ToolStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashTest.java
[JENKINS-45101](https://issues.jenkins-ci.org/browse/JENKINS-45101)
Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/27.
Does not cover every case. Most notably,
```groovy
junit testResults: '*.xml', keepLongStdio: true
```
is not supported, because this would require changes in `workflow-api`. (`argumentsToString` is currently given an unresolved map, which `workflow-basic-steps` _could_ resolve in the same manner as `ArgumentsAction.getResolvedArguments`, but then it would be duplicating code which is also due for a rewrite as described in comments there.) Good enough for now.
@reviewbybees
> [JENKINS-45101] argumentsToString implementations

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/FileExistsStep.java
- src/main/resources/org/jenkinsci/plugins/workflow/steps/Messages.properties
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/FileExistsStepTest.java
[JENKINS-48138](https://issues.jenkins-ci.org/browse/JENKINS-48138)
> [FIXED JENKINS-48138] Log a warning when fileExists called with empty string

- src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
- src/main/resources/org/jenkinsci/plugins/workflow/steps/TimeoutStep/config.jelly
- src/main/resources/org/jenkinsci/plugins/workflow/steps/TimeoutStep/help-activity.html
- src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java
[JENKINS-26521](https://issues.jenkins-ci.org/browse/JENKINS-26521)
Replaces #18 
Many thanks to @ikedam for the original version of this. I've just resurrected it and tweaked a couple things.
> [FIXED JENKINS-26521] Add activity flag to timeout step

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/ReadFileStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/WriteFileStep.java
- src/main/resources/org/jenkinsci/plugins/workflow/steps/ReadFileStep/help-encoding.html
- src/main/resources/org/jenkinsci/plugins/workflow/steps/WriteFileStep/help-encoding.html
- src/test/java/org/jenkinsci/plugins/workflow/steps/ReadWriteFileStepTest.java
See [JENKINS-52313](https://issues.jenkins-ci.org/browse/JENKINS-52313).
Adds support for a special encoding named "Base64" that can be used for binary files. Useful in tandem with jenkinsci/workflow-cps-global-lib-plugin#48 to copy binary resource files from shared libraries to the workspace.
~I'd prefer to use Java 8's Base64 API but the plugin is currently building against Java 7 so I am using commons-compress via Jenkins core.~ Baseline has been updated to Java 8 and Jenkins 2.60.3 to use the new Base64 API.
Also, I'm not sure if we want to add features to the stable branch or if that should be limited to the bleeding-edge branch, so just let me know if I need to rebase the PR.
@reviewbybees @jennbriden
> [JENKINS-52313] Add Base64 encoding to ReadFileStep and WriteFileStep for binary data

- .mvn/extensions.xml
- pom.xml
(Note: this is against master, not stable) Picks up [version 3.18](https://github.com/jenkinsci/plugin-pom/blob/master/CHANGELOG.md#318) of the parent pom which automatically runs the `incrementals:reincrementalify` Maven goal when preparing the plugin for the next development version after a release.
> Update parent for auto-reincrementalification when releasing

- src/main/resources/org/jenkinsci/plugins/workflow/steps/TimeoutStep/config.jelly
A small typo in #61 caused the text to be displayed as literally `$%{Timeout}`.
> Fix typo in TimeoutStep's config.jelly

- src/main/java/org/jenkinsci/plugins/workflow/steps/WriteFileStep.java
Fixes a file leak specific to Base64 encoding introduced by #66. Similar to jenkinsci/workflow-cps-global-lib-plugin#52.
@reviewbybees
> Fix file leak in WriteFileStep when using Base64 encoding

- src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java
See [JENKINS-54607](https://issues.jenkins-ci.org/browse/JENKINS-54607).
This PR enables the intended behaviour that the timeout step sleeps for a predefined `GRACE_PERIOD` till the body will be forcefully canceled.
Otherwise a `timeout(10)` results in waiting 10 additional minutes till the execution will be forcefully canceled
> [JENKINS-54607] Use Grace_Period for timeout

- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java
This is based on the analysis https://ci.jenkins.io/job/Infra/job/deprecated-usage-in-plugins/job/master/566/artifact/output/usage-by-plugin.html.
> Avoid deprecated api usage

- src/main/resources/org/jenkinsci/plugins/workflow/steps/Messages.properties
619226b270cae47130a724a517ef8a5b3d6bac6f introduced a stray `"` I guess copied from the Java string (use one of the IDE plugins for Jenkins which handle this!), and also I guess you forgot that `MessageFormat` treats `'` as a metacharacter unless doubled up to escape (generally better to avoid `'` and use `‘’` or something else). Currently prints:
```
[Pipeline] archive
The archive step is deprecated, please use archiveArtifacts instead."
```
> Fixing minor mistakes in messages

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/PushdStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/PushdStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/WithContextStepTest.java
Downstream of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/101.
> [JENKINS-41854] Recontextualizing FilePath on demand

- pom.xml
Accidentally released with a compile-scope incremental dependency yesterday.
> Use released version of workflow-durable-task-step

- src/main/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep.java
- src/main/resources/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep/config.jelly
- src/main/resources/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep/help-initialRecurrencePeriod.html
- src/test/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStepTest.java
Starting from 250msec and ramping up through two orders of magnitude for very slow operations causes a lot of log spew. Allow setting the initial recurrence period to something other than the default.  We often set it to 15 seconds, as we know up front that we'll need to wait about a minute for some async operations.
> Add an optional initialRecurrencePeriod arg to the waitUntil() step.

- src/test/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/DeleteDirStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/ReadWriteFileStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/WithContextStepTest.java
While looking at the test suite for this plugin, I noticed the `CpsFlowDefinition`s in the tests don't  consistently use the script security sandbox. In one case a comment was left saying "TODO sandbox fails on `staticMethod org.jenkinsci.plugins.workflow.cps.Safepoint safepoint`; why?", but this comment appears to be out-of-date since the failure no longer occurs on `master` as of the time of this writing. Always using the script security sandbox makes the tests consistent with each other, and it's also a more realistic environment given that the script security sandbox should always be enabled in production.
All existing tests passed when run in the script security sandbox, except for `WithContextStepTest#pushd`. To make this test pass, I approved the `method hudson.FilePath child …
> Consistently use sandbox for CpsFlowDefinitions

- src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/RetryStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/ToolStepTest.java
While perusing the source tree, I noticed a number of deprecated methods:
- The documentation for [`User.get(java.lang.String)`](https://javadoc.jenkins-ci.org/hudson/model/User.html#get-java.lang.String-) states: "This method is deprecated, because it causes unexpected `User` creation by API usage code and causes performance degradation of used to retrieve users by ID. Use [`getById(java.lang.String, boolean)`](https://javadoc.jenkins-ci.org/hudson/model/User.html#getById-java.lang.String-boolean-) when you know you have an ID."
- The documentation for [`ACL.impersonate(org.acegisecurity.Authentication, java.lang.Runnable)`](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#impersonate-org.acegisecurity.Authentication-java.lang.Runnable-) states: "use try with resources and …
> Remove usages of deprecated APIs

- src/main/java/org/jenkinsci/plugins/workflow/steps/PwdStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/PwdStepTest.java
In ad40c76, the `PwdStep#tempDir` method was added with a TODO comment to switch to `WorkspaceList.tempDir` when the baseline was bumped to 1.652. The baseline is now 2.150.1, so this TODO can be completed.
I confirmed that the code in question is exercised by `PwdStepTest#tmp`.
> Use WorkspaceList.tempDir

- src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStepExecution.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/RetryStepTest.java
In #36, a call to `Functions.printThrowable` was added with a TODO comment to switch to `Functions.printStackTrace` when the baseline was bumped to 2.43+. The baseline is now 2.150.1, so this TODO can be completed.
This code didn't have any test coverage, so I added a simple integration test which passes both before and after the changes in `src/main`.
> Use Functions.printStackTrace

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStepExecution.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/RetryStepTest.java
See [JENKINS-60354](https://issues.jenkins-ci.org/browse/JENKINS-60354) and https://github.com/jenkinsci/workflow-step-api-plugin/pull/51.
> [JENKINS-60354] Use FlowInterruptedException.isActualInterruption to decide if an exception should be rethrown

- src/main/resources/org/jenkinsci/plugins/workflow/steps/WithContextStep/help.html
[JENKINS-59575](https://issues.jenkins-ci.org/browse/JENKINS-59575)
If there were a formal way to deprecate a step (beyond `isAdvanced`) I would use it. These steps should never have been defined. I had originally thought to use them with the likes of https://github.com/jenkinsci/workflow-cps-plugin/pull/59.
> [JENKINS-59575] Warning about get/withContext

- src/main/java/org/jenkinsci/plugins/workflow/steps/FileExistsStep.java
- src/main/resources/org/jenkinsci/plugins/workflow/steps/Messages.properties
- src/test/java/org/jenkinsci/plugins/workflow/steps/FileExistsStepTest.java
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
fileExists can be called with a null parameter but will throw an NPE. Avoid the NPE by using a blank string instead.
> Avoid NPE when calling fileExists step

- src/test/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStepTest.java
Hi we're experiencing flakey tests trying to integrate the next bom line,
example:
```
Expected: a string containing "broken condition"
but: was "Started
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] waitUntil
[Pipeline] {
[Pipeline] semaphore
[Pipeline] }
Will try again after 0.25 sec
[Pipeline] {
[Pipeline] semaphore
[Pipeline] }
[Pipeline] // waitUntil
[Pipeline] End of Pipeline
```
@jglick suggested replacing assertLogContains with waitForMessage
https://github.com/jenkinsci/bom/pull/110#issuecomment-594782396
> Use waitForMessage in tests to reduce flakes

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/PwdStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/WriteFileStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
Subsumes #116. See [JENKINS-29144](https://issues.jenkins-ci.org/browse/JENKINS-29144).
This PR adds some minor formatting changes, updates the Jenkinsfile to test against 2.241 as well as the current baseline, and changes `CoreStep` from using the Jenkins version to decide whether to call the new overload of `perform` to directly check for the new method instead.
> [JENKINS-29144] Extend CoreStep to also pass EnvVars to SimpleBuildStep

- src/main/resources/org/jenkinsci/plugins/workflow/steps/SleepStep/help-time.html
- src/main/resources/org/jenkinsci/plugins/workflow/steps/SleepStep/help-unit.html
- src/main/resources/org/jenkinsci/plugins/workflow/steps/TimeoutStep/help-time.html
- src/main/resources/org/jenkinsci/plugins/workflow/steps/TimeoutStep/help-unit.html
- src/main/resources/org/jenkinsci/plugins/workflow/steps/TimeoutStep/help.html
Updates the help text for the `sleep` and `timeout` steps, mainly to mention the default unit for the `unit` parameters for each step in dedicated `help-$field.html` files . Subsumes #46 and #14.
> Improve help text for the sleep and timeout steps

- src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java
This test is invalid and should not have been added in https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/83, see https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/116#discussion_r436741358. Essentially, the test was passing, but for the wrong reason. The expectation was that the step would run and "caught error" would be printed to the logs, but what was actually happening was that the step could not be instantiated because the `message` parameter is optional and so must be specified like this: `message: 'blah'`, but the test was passing because "caught error" showed up in the exception thrown when the step could not be instantiated.
> Remove CatchErrorStepTest.optionalMessage because it is invalid

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
Same as #127 but also updates the Jenkinsfile to stop building against 2.241.
> [JENKINS-29144] Require Jenkins 2.249.1 or newer to avoid reflection

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
#121 caused test failures in `artifact-manager-s3` when on 2.249.x for good reason: `AbortException` was being wrapped in `InvocationTargetException` and thus displaying an ugly stack trace rather than a nice `ERROR` message. Probably `FlowInterruptedException` would have been broken as well, messing up build statuses, termination causes, etc.
Can be corrected by catching `InvocationTargetException` but simpler to just use the LTS dep already and keep the code clean.
> [JENKINS-29144] 2.249.x dep to avoid reflection & InvocationTargetException

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
This is a variation of https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/117, using the API changes from https://github.com/jenkinsci/jenkins/pull/4829.
Also contains the `PwdStep` fix from https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/122.
Marking as draft because there are multiple variations, both here and at the core level.
> [JENKINS-46175] Make workspace context optional for CoreStep and CoreWrapperStep.

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
- src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
#123 mistakenly kept an override of `Disposer.requiresWorkspace`, which in the ultimate version of the API was not necessary (this method need only be overridden in `SimpleBuildWrapper`), and is in fact `final`. Because of reflection, this mistake was not noticed until PCT uncovered it in https://github.com/jenkinsci/bom/pull/339.
> Disposer.requiresWorkspace is final

- src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java
Increase the time sleep before the next print.
This should never fail as it likely will be force killed after 5 seconds.
See https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/132#issuecomment-723038487
> Reduce flakiness of windows timeout test

- src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
Discovered in jenkinsci/bom#423. Like jenkinsci/workflow-support-plugin#114 and jenkinsci/git-client-plugin#686, but for `workflow-basic-steps`.
`workflow-basic-steps` previously used `MoreExecutors#sameThreadExecutor` from Guava, which was removed in version 21.0 in favor of `MoreExecutors#newDirectExecutorService`. This PR uses reflection to first try to call `MoreExecutors#newDirectExecutorService` but then call `MoreExecutors#sameThreadExecutor` if the first method is not available to support both older and newer versions of Guava.
> Make `workflow-basic-steps` compatible with Guava 21.0 and newer

- src/test/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashTest.java
Seen for example in https://github.com/jenkinsci/bom/pull/357. As can be seen in https://github.com/jenkinsci/workflow-job-plugin/blob/32090697af62e9513de78dd1ed096a6bace8651e/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java#L639-L643 the build is marked completed just before stashes are cleared.
> Corrected flakes in StashTest

- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/EnvStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/FileExistsStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/PushdStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/SleepStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStepTest.java
We seem to be generally preferring `JenkinsSessionRule` to `RestartableJenkinsRule`. The main benefit to `JenkinsSessionRule` is that `#then` runs immediately, so it plays nicely with things like `@After.`
> Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`

- src/main/resources/org/jenkinsci/plugins/workflow/steps/PwdStep/help-tmp.html
The pwd(tmp:true) does not return tmp directory for the workspace, but the return value is different for each current directory. The description was misleading suggesting it is associated with the workspace.
> Document pwd(tmp:true) is for the current dir

- src/main/resources/org/jenkinsci/plugins/workflow/steps/FileExistsStep/help-file.html
- src/main/resources/org/jenkinsci/plugins/workflow/steps/FileExistsStep/help.html
While working on https://github.com/jenkins-infra/pipeline-library/pull/232#pullrequestreview-776290117, I stumbled on the current documentation of the `fileExists` step.
This PR aims at adding examples and specifying a bit more what this step can do.
> doc [fileExists step] specify that absolute and Windows paths are allowed + add examples

- src/test/java/org/jenkinsci/plugins/workflow/steps/PushdStepTest.java
Checking compatibility of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180.
See https://github.com/jenkinsci/jenkins-test-harness/pull/344.
> Strengthen `PushdStepTest.restarting` to use an agent

- pom.xml
Downstream of #166 and jenkinsci/jenkins#6165. Bumps the baseline to one containing jenkinsci/jenkins#6165, thus using the detached JavaMail plugin, but does not upgrade to Jakarta Mail.
> Use detached JavaMail plugin

- src/main/resources/org/jenkinsci/plugins/workflow/steps/EnvStep/help.html
Document that environment variables are case insensitive but case preserving as per https://javadoc.jenkins.io/hudson/EnvVars.html#:~:text=So%20for%20a%20consistent%20cross%20platform%20behavior%2C%20it%20creates%20the%20least%20confusion%20to%20make%20the%20table%20case%20insensitive%20but%20case%20preserving.
> document environment variables are case insensitive

- pom.xml
Supersedes #183. Cleans up from #167. Could be a starting point for #168.
> Switch to `bom-2.332.x`

- src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStep.java
It may not be intuitive that
```groovy
retry(1) {
something()
}
```
is equivalent to just
```groovy
something()
```
and that you actually need to specify a `count` of at least 2 in order to have any useful functionality.
> Add form validation for `RetryStep.count`

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/steps/MailStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/MailStepTest.java
Downstream of #166, #167, and jenkinsci/jenkins#6165. Bumps the baseline to one containing jenkinsci/jenkins#6165 and migrates to Jakarta Mail.
> Migrate to Jakarta Mail

- src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java
Cloudbees CI reported a that [CatchErrorStepTest#catchesInterruptionsByDefault](https://github.com/Pldi23/workflow-basic-steps-plugin/blob/e6731c5a9e39737be611cb0bb6a7f321e98ad967/src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java#L165) is flaky.
Logs:
[stderr_BEE-18075.txt](https://github.com/jenkinsci/workflow-basic-steps-plugin/files/9267134/stderr_BEE-18075.txt)
[stacktrace_BEE-18075.txt](https://github.com/jenkinsci/workflow-basic-steps-plugin/files/9267135/stacktrace_BEE-18075.txt)
Solution:
Avoid any sensitivity to timing by removing timeout step and throwing directly.
> Fix flaky CatchErrorStepTest 

- src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
Cloudbees CI reported a flakiness in TimeoutStepExecutionTest#activityRestart.
Logs:
[activityRestart_stacktrace.txt](https://github.com/jenkinsci/workflow-basic-steps-plugin/files/9297931/activityRestart_stacktrace.txt)
[activityRestart_stderr.txt](https://github.com/jenkinsci/workflow-basic-steps-plugin/files/9297933/activityRestart_stderr.txt)
The issue could be reproduced locally, (test crashes quite often), when after restart timeout set to expire in less then 7.5 sec the test fails.
```
1.281 [restarted #1] Timeout set to expire after 3.3 sec without activity
```
From what I see the reason of the flake is the race condition between Tick (which gets scheduled with timeout / 2, in our particular case 7.5 sec) and Killer's delay (which is after restart in our particular case was 3.3 …
> Call ResetTimer synchronously from eol and skip the Tick when channel is null

- src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java
#226 correctly diagnosed a problem brought to light by a flaky test, but the fix was not correct (only applied to messages printed within the controller as opposed to from an agent) and apparently introduced a severe performance regression.
I think the root issue was that restarting the controller ought to count as “activity” for purposes of delaying the timeout (better to err on the side of caution) but it did not.
> Better fix of `timeout` activity tick after restart

- src/main/resources/org/jenkinsci/plugins/workflow/steps/FileExistsStep/help-file.html
- src/main/resources/org/jenkinsci/plugins/workflow/steps/FileExistsStep/help.html
Reported in [documentation feedback sheet](https://docs.google.com/spreadsheets/d/1nA8xVOkyKmZ8oTYSLdwjborT0w-BpBNNZT0nxR9deZ8/edit#gid=1087292709)
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
> Fix Pipeline syntax in `fileExists` examples

- src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help.html
#291 reminded me of an important point that had been forgotten here.
> Noting `artifact-manager-s3` impact on `stash`

- src/main/java/org/jenkinsci/plugins/workflow/steps/ToolStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/ToolStepTest.java
Tools page doesn't prevent submission of empty tool names. Some tools (e.g. Allure Commandline) use `Util.fixEmptyAndTrim` on the name, so there is a possibility of NPE when comparing the tool names. By flipping the comparison we avoid NPE since `tool` step requires `name` argument.
This most likely fixes https://issues.jenkins.io/browse/JENKINS-61474
```[tasklist]
```
> JENKINS-61474 Improve null safety of the tool step

- src/main/resources/org/jenkinsci/plugins/workflow/steps/FileExistsStep/help.html
As can be seen from the code comments, the two examples were mixed up. I switched them into the correct order.
This is not a big change, so I don't think an extra issue or testing is needed?
```[tasklist]
```
> Correct switched pipeline examples

- src/main/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStep.java
- src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java
Otherwise it can be confusing why a build had the result that it did. Observed in a pipeline using the idiom
```groovy
retry(count: 2, conditions: [kubernetesAgent(), nonresumable()]) {
node(POD_LABEL) {
stage('build') {
withMockLoad(averageDuration: 180) {
catchError(buildResult: 'UNSTABLE') {
sh MOCK_LOAD_COMMAND
}
}
}
stage('publish') {
junit 'mock-junit.xml'
archiveArtifacts artifacts: 'mock-artifact-*.txt', allowEmptyArchive: true, fingerprint: true
}
}
}
```
When the first pod is killed, the `node` block retried and the build ran to completion (`FlowEndNode` set to `SUCCESS`) yet the `Run` is set to `UNSTABLE`, which is what the step is supposed to do but unintentional here; the reason for the `catchError` was rather to work around an exit code of 1 from the mock load command due to …
> Log a note when `catchError` sets build result

- pom.xml
Reverting a small bit of cleanup from #321 as it is unrelated to the core Jakarta EE 9 effort and seems to be causing various cryptic PCT failures as seen in https://github.com/jenkinsci/bom/pull/4302.
> Revert cleanup from #321
