jenkinsci/workflow-basic-steps-plugin

src/main/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/PushdStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java

[JENKINS-26156] Remove calls to BodyInvoker.withDisplayName(null)

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/SleepStep.java

Implementation of https://github.com/jenkinsci/workflow-step-api-plugin/pull/4.
@reviewbybees

[JENKINS-31842] Thread dump improvements

---

src/main/java/org/jenkinsci/plugins/workflow/steps/MailStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/MailStepTest.java

[JENKINS-29170](https://issues.jenkins-ci.org/browse/JENKINS-29170)
@reviewbybees

JENKINS-29170 - `Util.fixEmpty` `charset` and `mimeType`

---

src/main/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep.java

Implements [JENKINS-34554](https://issues.jenkins-ci.org/browse/JENKINS-34554).  Wasn't entirely sure how to implement a test (or if one was necessary).

[FIXED JENKINS-34554] WaitForConditionStep: introduce maximum recurrence period

---

src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help.html

Cf. https://github.com/jenkinsci/workflow-api-plugin/pull/19. Suggested by jfemia on #jenkins.
@reviewbybees

[JENKINS-38640] [JENKINS-36914] Warn users to avoid stash/unstash of large files

---

src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepRunTest.java

https://issues.jenkins-ci.org/browse/JENKINS-34637

Add test case to reproduce JENKINS-34637.

---

src/main/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep.java

Implemented getStatus for waitUntil

---

src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java

Cf. https://github.com/jenkinsci/jenkins/pull/2450 & https://github.com/jenkinsci/jenkins/pull/2630.
@reviewbybees esp. @recena

Adjust test to work against -Djenkins.version=2.19.4

---

.gitignore
src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/RetryStepTest.java

See [JENKINS-41276](https://issues.jenkins-ci.org/browse/JENKINS-41276)
@reviewbybees

[JENKINS-41276] Do not retry if user aborted the build

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/EnvStepRunTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/ToolStepRunTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/ToolStepTest.java

Added a Jenkinsfile

---

src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help.html

Update stash step help to suggest size guidelines

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/config.jelly
src/test/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashTest.java

Depends on https://github.com/jenkinsci/workflow-api-plugin/pull/35

[JENKINS-37327] allow empty stash.

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStep/help.html
src/main/resources/org/jenkinsci/plugins/workflow/steps/Messages.properties
src/test/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java

[JENKINS-46178](https://issues.jenkins-ci.org/browse/JENKINS-46178), [JENKINS-46179](https://issues.jenkins-ci.org/browse/JENKINS-46179)
Both in help message in snippet generator and a message echoed to the
console log when the step is actually run.

[FIXED JENKINS-46179, JENKINS-46178] Clarify archive deprecation

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/EnvStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/PushdStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/steps/SleepStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/WithContextStep.java

Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/30.
@reviewbybees

[JENKINS-26148] Using default implementation of StepExecution.stop

---

src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/steps/Messages.properties
src/test/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStepTest.java

[JENKINS-46180](https://issues.jenkins-ci.org/browse/JENKINS-46180)

[FIXED JENKINS-46180] Log when no files found for archive step.

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/RetryStepTest.java

[JENKINS-44379](https://issues.jenkins-ci.org/browse/JENKINS-44379)

[FIXED JENKINS-44379] Don't retry for any FlowInterruptedException

---

src/main/resources/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStep/help-excludes.html
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help-excludes.html
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help-includes.html

* Make the three articles consistent
* Use target="_blank" for each link
* Fix stray `"` character
* Include link to dir() pipeline step

minor: improve stash help

---

src/main/resources/org/jenkinsci/plugins/workflow/steps/TimeoutStep/help.html

Using `Exception` is not best idea, better to catch this specific exception

Add exception name in TimeoutStep help

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java

Using https://github.com/jenkinsci/workflow-step-api-plugin/pull/38 to solve [JENKINS-43276](https://issues.jenkins-ci.org/browse/JENKINS-43276) at last.

[JENKINS-43276] Using GeneralNonBlockingStepExecution

---

src/main/resources/org/jenkinsci/plugins/workflow/steps/WarnErrorStep/help.html

Noticed a few typos while preparing release notes for the plugin.

[JENKINS-45579] Fix typos and reword warnError help text

---

CHANGELOG.md
README.md
pom.xml

Migrate wiki content to GitHub and add 2.19 release notes

---

src/main/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep.java
src/main/resources/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep/help-quiet.html
src/test/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStepTest.java

I did my best to adhere to existing patterns. I'm assuming this feature is relatively uncontroversial given the lack of discussion on [the related ticket](https://issues.jenkins-ci.org/browse/JENKINS-59776).

[JENKINS-59776] Add quiet option to waitUntil

---

CHANGELOG.md

Add release notes for 2.20

---

src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java

Flake noted in #44 and just seen in PCT: https://github.com/jenkinsci/bom/pull/257#issuecomment-648408234

TimeoutStepTest.timeIsConsumed is flaky

---

src/main/resources/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep/help-initialRecurrencePeriod.html
src/main/resources/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep/help.html

Add clarification to the maximum wait time between retries in the helper

Update Helper text with max wait time

---

CHANGELOG.md

Add release notes for 2.21

---

src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java

Adding a test for windows that effectively does the same thing as the linux test

Add test for timeoutstep with batch script for windows

---

CHANGELOG.md

Add release notes for 2.22

---

src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java

Improves testing for the Windows platform, with this both windows and unix have an equivalent number of tests

Add Windows tests for CoreWrapperStep

---

CHANGELOG.md

Add release notes for 2.23

---

src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java

Make it possible to detect whether a FlowInterruptedException was caught inside or outside the timeout block that generated it. Workaround for [JENKINS-51928](https://issues.jenkins-ci.org/browse/JENKINS-51928) – user code can now decide to rethrow or not.
I made the constructor of `ExceededTimeout` private. In theory this is a breaking change; but I presumed it's improbable that external code was using it. Let me know if you agree.
Also, I wanted to add another check to the `serialForm` test to make sure future code stays compatible with this form as well, but I could not figure out how to do it. I tried creating a job similar to what the test already uses, and copy out the files (`program.dat` etc) while it is running, but for some reason it appears not to resume correctly under …

Make it possible to detect source of timeout

---

CHANGELOG.md

add 2.24 to changelog

---

src/main/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/CatchExecutionOptions.java
src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/MailStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/steps/ToolStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/UnstashStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java

EOL JSR 305

---

src/main/resources/org/jenkinsci/plugins/workflow/steps/CatchErrorStep/help-catchInterruptions.html
src/main/resources/org/jenkinsci/plugins/workflow/steps/PwdStep/help-tmp.html
src/main/resources/org/jenkinsci/plugins/workflow/steps/TimeoutStep/help-activity.html
src/main/resources/org/jenkinsci/plugins/workflow/steps/WarnErrorStep/help-catchInterruptions.html
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help-useDefaultExcludes.html

[ JENKINS-65449
](https://issues.jenkins.io/browse/JENKINS-65449)
Based on row 449 of this excel [sheet](https://docs.google.com/spreadsheets/d/1nA8xVOkyKmZ8oTYSLdwjborT0w-BpBNNZT0nxR9deZ8/edit#gid=1087292709), people are asking for default values of the boolean arguments. 
@aHenryJard @MarkEWaite @Stackscribe @kwhetstone

[JENKINS-65449] Add default values

---

src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java

Extracted from https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/195. See https://github.com/jenkinsci/jenkins-test-harness/pull/428.

Analogue of JTH change for `createSpecialEnvSlave`

---

src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help.html

Simplify the phrasing of the online help slightly.
Confirmed the text is changed in the help file using `git diff`.  No other testing performed.

Replace 'master' with 'controller' in help

---

src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java

Just a scenario that was not immediately obvious to me and I wanted to verify how it works.

Added `CatchErrorStepTest.abortPreviousWithCatchError`

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStepTest.java

https://github.com/jenkinsci/workflow-step-api-plugin/pull/197

Using `StepExecution.acceptAll`
